'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

const tabs=['overview','users','sliders','banners','video','telegram','notifications','trash','activity'];
const empty={users:[],slides:[],banners:[],notifications:[],trash:[],activity:[],video:null,telegram:null};
const label=(v)=>v.charAt(0).toUpperCase()+v.slice(1).replaceAll('_',' ');
const show=(v)=>v==null||v===''?'—':typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)?new Date(v).toLocaleString():String(v);

export default function AdminDashboard(){
 const router=useRouter(),[data,setData]=useState(null),[tab,setTab]=useState('overview'),[message,setMessage]=useState('');
 async function refresh(){const r=await fetch('/api/admin/overview',{cache:'no-store'});if(r.status===401){router.replace('/admin/login');return;}setData(r.ok?await r.json():empty)}
 useEffect(()=>{refresh().catch(()=>setData(empty))},[]);
 async function save(resource,values,id){setMessage('Saving…');const r=await fetch('/api/admin/resource',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource,values,id})});const result=await r.json();setMessage(r.ok?'Saved successfully.':result.error||'Unable to save.');if(r.ok)await refresh()}
 async function remove(resource,id){if(!window.confirm('Remove this item?'))return;const r=await fetch('/api/admin/resource',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource,id})});setMessage(r.ok?'Removed successfully.':'Unable to remove.');if(r.ok)await refresh()}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});router.replace('/admin/login')}
 if(!data)return <main className="center-screen">Loading admin dashboard…</main>;
 return <main className="admin-shell"><aside><h1>TopPay Admin</h1>{tabs.map(name=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{label(name)}</button>)}<button onClick={logout}>Logout</button></aside><section><div className="section-heading"><div><h2>{label(tab)}</h2><p>React full-stack control panel</p></div><button className="outline-button" onClick={refresh}>Refresh</button></div>{message&&<p className="admin-message">{message}</p>}{tab==='overview'&&<Overview data={data}/>} {tab==='users'&&<SimpleTable rows={data.users} columns={['mobile','mpin','status','login_count','created_at']} format={{mpin:v=>v?'Set':'Not set'}}/>}{tab==='sliders'&&<Media resource="sliders" rows={data.slides} save={save} remove={remove}/>} {tab==='banners'&&<Media resource="banners" rows={data.banners} save={save} remove={remove}/>} {tab==='video'&&<Setting resource="video" item={data.video} save={save}/>} {tab==='telegram'&&<Setting resource="telegram" item={data.telegram} save={save}/>} {tab==='notifications'&&<Notifications rows={data.notifications} save={save} remove={remove}/>} {tab==='trash'&&<SimpleTable rows={data.trash} columns={['original_table','record_id','deleted_at']}/>} {tab==='activity'&&<SimpleTable rows={data.activity} columns={['action','details','created_at']}/>}</section></main>
}
function Overview({data}){return <div className="metric-grid">{[['Users',data.users.length],['Sliders',data.slides.length],['Banners',data.banners.length],['Notifications',data.notifications.length],['Trash',data.trash.length],['Activity events',data.activity.length]].map(([n,v])=><article key={n}><small>{n}</small><strong>{v}</strong></article>)}</div>}
function SimpleTable({rows,columns,format={}}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{label(c)}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i}>{columns.map(c=><td key={c}>{format[c]?format[c](row[c]):show(row[c])}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}>No records found.</td></tr>}</tbody></table></div>}
function Media({resource,rows,save,remove}){const[url,setUrl]=useState(''),[title,setTitle]=useState('');function submit(e){e.preventDefault();save(resource,{image_url:url,title,display_order:rows.length,is_enabled:true});setUrl('');setTitle('')}return <><form className="admin-form" onSubmit={submit}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title"/><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="Image URL" required/><button className="primary">Add</button></form><div className="cards">{rows.map(item=><article key={item.id}><img src={item.image_url} alt={item.title||label(resource)}/><strong>{item.title||'Untitled'}</strong><small>{item.is_enabled===false?'Disabled':'Enabled'}</small><button className="danger-button" onClick={()=>remove(resource,item.id)}>Remove</button></article>)}</div></>}
function Setting({resource,item,save}){const video=resource==='video',key=video?'video_url':'telegram_link',[url,setUrl]=useState(item?.[key]||''),[title,setTitle]=useState(item?.title||''),[desc,setDesc]=useState(item?.description||''),[enabled,setEnabled]=useState(Boolean(item?.is_enabled));function submit(e){e.preventDefault();save(resource,{[key]:url,title,...(video?{}:{description:desc}),is_enabled:enabled},item?.id)}return <form className="settings-form" onSubmit={submit}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{video?'Video URL':'Telegram URL'}<input type="url" value={url} onChange={e=>setUrl(e.target.value)} required/></label>{!video&&<label>Description<textarea value={desc} onChange={e=>setDesc(e.target.value)}/></label>}<label className="check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enabled</label><button className="primary">Save settings</button></form>}
function Notifications({rows,save,remove}){const[title,setTitle]=useState(''),[message,setMessage]=useState('');function submit(e){e.preventDefault();save('notifications',{title,message,type:'info',is_read:false});setTitle('');setMessage('')}return <><form className="admin-form" onSubmit={submit}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" required/><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message" required/><button className="primary">Create</button></form><div className="list">{rows.map(item=><article key={item.id}><div><strong>{item.title}</strong><p>{item.message}</p></div><button className="danger-button" onClick={()=>remove('notifications',item.id)}>Remove</button></article>)}</div></>}
